import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";

const inter = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Portfolio On Trial",
    description: "Generated by create next app",
};

interface Props {
    children: React.ReactNode;
}

export default function RootLayout({ children }: Props) {
    return (
        <html lang="es">
            <body
                className={inter.className}
                style={{
                    backgroundColor: "#2C282E",
                    backgroundRepeat: "no-repeat",
                }}
            >
                {children}
            </body>
        </html>
    );
}
